export const PERMISSIONS = {
  // Campaign Management
  CAMPAIGNS_CREATE: 'campaigns:create',
  CAMPAIGNS_EDIT: 'campaigns:edit', 
  CAMPAIGNS_VIEW: 'campaigns:view',
  CAMPAIGNS_SHARE: 'campaigns:share',
  
  // Asset Management
  ASSETS_CREATE: 'assets:create',
  ASSETS_EDIT: 'assets:edit',
  ASSETS_VIEW: 'assets:view', 
  ASSETS_SHARE: 'assets:share',
  
  // Campaign Plans
  PLANS_CREATE: 'plans:create',
  PLANS_EDIT: 'plans:edit',
  PLANS_VIEW: 'plans:view',
  PLANS_SHARE: 'plans:share',
  
  // Team Management
  TEAM_ADD_REMOVE: 'team:add_remove',
  TEAM_VIEW: 'team:view',
  
  // Organisation Management  
  ORG_ADD_REMOVE: 'organisation:add_remove',
  ORG_VIEW: 'organisation:view',
  AUDIENCE_PLAN_VIEW: 'audience_plan:view',
  AUDIENCE_PLAN_EDIT: 'audience_plan:edit',

  // Proof of Play
  POPS_MANAGE: 'pops:manage',
};

export const ROLE_PERMISSIONS = {
  'Superadmin': Object.values(PERMISSIONS),
  
  'Media Owner Admin': Object.values(PERMISSIONS),
  
  'Media Owner User': [
    PERMISSIONS.CAMPAIGNS_CREATE, PERMISSIONS.CAMPAIGNS_EDIT, PERMISSIONS.CAMPAIGNS_VIEW, PERMISSIONS.CAMPAIGNS_SHARE,
    PERMISSIONS.ASSETS_CREATE, PERMISSIONS.ASSETS_EDIT, PERMISSIONS.ASSETS_VIEW, PERMISSIONS.ASSETS_SHARE,
    PERMISSIONS.PLANS_CREATE, PERMISSIONS.PLANS_EDIT, PERMISSIONS.PLANS_VIEW, PERMISSIONS.PLANS_SHARE,
    PERMISSIONS.TEAM_VIEW,
    PERMISSIONS.ORG_VIEW, PERMISSIONS.AUDIENCE_PLAN_VIEW, PERMISSIONS.AUDIENCE_PLAN_EDIT
  ],
  
  'Media Agency Admin': [
    PERMISSIONS.CAMPAIGNS_VIEW, PERMISSIONS.CAMPAIGNS_SHARE,
    PERMISSIONS.PLANS_CREATE, PERMISSIONS.PLANS_EDIT, PERMISSIONS.PLANS_VIEW, PERMISSIONS.PLANS_SHARE,
    PERMISSIONS.TEAM_ADD_REMOVE, PERMISSIONS.TEAM_VIEW, PERMISSIONS.AUDIENCE_PLAN_VIEW, PERMISSIONS.AUDIENCE_PLAN_EDIT
  ],
  
  'Media Agency User': [
    PERMISSIONS.CAMPAIGNS_VIEW, PERMISSIONS.CAMPAIGNS_SHARE,
    PERMISSIONS.PLANS_CREATE, PERMISSIONS.PLANS_EDIT, PERMISSIONS.PLANS_VIEW, PERMISSIONS.PLANS_SHARE,
    PERMISSIONS.TEAM_VIEW, PERMISSIONS.AUDIENCE_PLAN_VIEW, PERMISSIONS.AUDIENCE_PLAN_EDIT
  ],
  
  'Sales Rep': [
    PERMISSIONS.ASSETS_VIEW, PERMISSIONS.ASSETS_SHARE,
    PERMISSIONS.PLANS_CREATE, PERMISSIONS.PLANS_EDIT, PERMISSIONS.PLANS_VIEW, PERMISSIONS.PLANS_SHARE,
    PERMISSIONS.TEAM_VIEW, PERMISSIONS.AUDIENCE_PLAN_VIEW, PERMISSIONS.AUDIENCE_PLAN_EDIT
  ]
};